/*CREATE DATABASE IF NOT EXISTS ceasuri;

CREATE TABLE IF NOT EXISTS cumparator(
id INT(5) PRIMARY KEY AUTO_INCREMENT,
nume VARCHAR (30),
prenume VARCHAR(30),
adresa VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS produse(
idp INT(5) PRIMARY KEY AUTO_INCREMENT,
denumire VARCHAR(30),
model VARCHAR(30),
pret DOUBLE(5,2),
stoc INT(5)
);

CREATE TABLE IF NOT EXISTS vanzari(
id INT(5),
idp INT(5),
cantitate INT(5),
datav DATE
);
*/

SELECT * FROM produse;

